## Disease

## Disease Data
```{r}
#Reading in disease data
Disease <- read.csv("Disease2022.csv") %>% mutate(Lineage = recode(Lineage, FI="CL1", NEH="CL2")) %>%
  mutate(Type = ifelse(Lineage == "CL1" | Lineage == "CL2", "Commercial", "Wild")) %>%
#Creating columns for disease prevalence
  subset(Sample.ID != 'NR-209') %>%
  group_by(Lineage, Type) %>%
  mutate(Dermo_Infected = ifelse(Dermo.Intensity > 0, 1, 0)) %>%
  mutate(MSX_Infected = ifelse(MSX.Intensity > 0, 1, 0)) %>%
  mutate(SSO_Infected = ifelse(SSO.Intensity > 0, 1, 0)) 
```

Statistical test on disease intensity
```{r}
shapiro.test(Disease$Dermo.Intensity)
kruskal.test(Disease$Dermo.Intensity ~ Disease$Lineage)
dunn.test(Disease$Dermo.Intensity, g = Disease$Lineage, method  = "bonferroni")
shapiro.test(Disease$MSX.Intensity)
kruskal.test(Disease$MSX.Intensity ~ Disease$Lineage)
dunn.test(Disease$MSX.Intensity, g = Disease$Lineage, method  = "bonferroni")
```

Plotting disease intensity for Dermo and MSX
```{r}
Dermo <- ggplot(Disease, aes(x= Lineage, y=Dermo.Intensity, fill = Type))+
  #geom_boxplot()+
  geom_boxplot_pattern(aes(fill = Type, pattern_alpha = Type), lwd = 1)+
  scale_pattern_alpha_manual(values = c(1, 0))+
  theme_bw()+
  scale_fill_grey()+
  theme(
    axis.ticks.length=unit(-0.2, "cm"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    legend.position = "none",
    panel.border = element_blank(),
    panel.grid.minor = element_blank(),text = element_text(face = "bold"),
    axis.line.x = element_line(size = 1, linetype = "solid", colour = "black"),
    axis.line.y = element_line(size = 1, linetype = "solid", colour = "black"))+
  ggtitle("Dermo Intensity at 16 Months")+
  xlab("Population")+
  ylab("Intensity")
plot(Dermo)
MSX <- ggplot(Disease, aes(x= Lineage, y=MSX.Intensity, fill = Type))+
  #geom_boxplot()+
  geom_boxplot_pattern(aes(fill = Type, pattern_alpha = Type), lwd = 1)+
  scale_pattern_alpha_manual(values = c(1, 0))+
  theme_bw()+
  scale_fill_grey()+
  theme(
    axis.ticks.length=unit(-0.2, "cm"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    legend.position = c(0.8, 0.95),
    panel.border = element_blank(),
    panel.grid.minor = element_blank(),text = element_text(face = "bold"),
    axis.line.x = element_line(size = 1, linetype = "solid", colour = "black"),
    axis.line.y = element_line(size = 1, linetype = "solid", colour = "black"))+
  ylim(0,5)+
  ggtitle("MSX Intensity at 16 Months")+
  xlab("Population")+
  ylab("Intensity")
plot(MSX)
```

```{r}
plot_grid(Dermo, MSX, labels = c("A","B"))
```

