# Fst

```{r}
library(adegenet)
library(hierfstat)
library(vcfR)
library(tidyverse)
RISG_genind <- vcfR2genind(read.vcfR("../Filtering/RISG.vcf"))
Samples <- read.table("../GeneticDiversity/Samples.txt", header = TRUE) %>% 
  mutate(Population = recode(Population, FI = 'CL1', NEH = 'CL2'))
poplist.names <- Samples$Population
strata(RISG_genind) <- Samples
setPop(RISG_genind) <- ~Population
#Perloc <- wc(RISG_genind)
Fst <- as.data.frame(pairwise.WCfst(RISG_genind))
write.csv(Fst, "Fst.csv")
pheatmap(Fst, display_numbers = T, cellwidth=40, cellheight=40, main="Pairwise FST")
```

Next we need to determine the confidence intervals of these values to see if any are significantly high
```{r}
Boot_fst <- boot.ppfst(RISG, nboot=20000)
write.csv(as.data.frame(Boot_Hier$ll), "Boot_ll.csv")
write.csv(as.data.frame(Boot_Hier$ul), "Boot_ul.csv")
```

Now we can calculate p-values using these confidence intervals
```{r}
#P-Values for Fst
Fst_mean <- (Boot_Hier$ul + Boot_Hier$ll)/2
Fst_Est <- Fst_Hier-Fst_mean
Fst_SE <- (Boot_Hier$ul - Boot_Hier$ll)/(2*1.96)
Fst_z <- Fst_Est/Fst_SE
Fst_pval <- 2*(1-pnorm(abs(Fst_z)))
```


